version: '3'
services:
  app:
    build:
      context: .
      target: builder
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - .:/app # live reload only for development
      - /app/node_modules
    depends_on:
      - redis
    environment:
      NODE_ENV: dev

  redis:
    image: redis:8.4-alpine
    ports:
      - 6379:6379
    environment:
      - REDIS_HOST=redis